import { Wrench, Landmark, Construction, FileSliders } from "lucide-react";

export const ModuleMenus = [
    {
      id: "service",
      title: "GLORY SERVICE",
      subtitle: "Input & Manage Service Orders",
      desc: "Manajemen data servis, update status perbaikan, dan cetak nota fisik.",
      href: "/fl/dashboard/service",
      icon: Wrench,
      accent: "hover:border-orange-500/50 hover:shadow-orange-500/20",
      textAccent: "group-hover:text-orange-400",
      bgGradient: "from-orange-500/5 via-orange-500/10 to-transparent",
      iconBg: "bg-orange-500/10 border-orange-500/30",
      iconColor: "text-orange-400",
      stat: `ONLINE`,
      disabled: false,
    },
    {
      id: "bank",
      title: "GLORY BANK",
      subtitle: "Transfer Antar Bank",
      desc: "Input data transfer dan cetak struk.",
      href: "/fl/dashboard/bank",
      icon: Landmark,
      accent: "hover:border-cyan-500/50 hover:shadow-cyan-500/20",
      textAccent: "group-hover:text-cyan-400",
      bgGradient: "from-cyan-500/5 via-cyan-500/10 to-transparent",
      iconBg: "bg-cyan-500/10 border-cyan-500/30",
      iconColor: "text-cyan-400",
      stat: `ONLINE`,
      disabled: false,
    },
    {
      id: "treasury",
      title: "GLORY REKAP",
      subtitle: "Under Development",
      desc: "Modul ini sedang dalam pengembangan sistem. Akses ditutup sementara oleh Engineering.",
      href: "#",
      icon: Construction,
      accent: "border-yellow-900/30 border-dashed bg-yellow-900/5", 
      textAccent: "text-yellow-600",
      bgGradient: "from-transparent to-transparent",
      iconBg: "bg-yellow-900/10 border-yellow-900/30",
      iconColor: "text-yellow-600",
      stat: "MAINTENANCE",
      disabled: false,
    },
    {
      id: "secret",
      title: "CAPTAIN ONLY",
      subtitle: "For Recap and Check Only",
      desc: "Rekap Data Bank, dan Service All in one. control pelanggan dan lain lain",
      href: "/fl/dashboard/captain-only",
      icon: FileSliders,
      accent: "border-red-900/30 border-dashed bg-red-900/5", 
      textAccent: "text-red-600",
      bgGradient: "from-transparent to-transparent",
      iconBg: "bg-red-900/10 border-red-900/30",
      iconColor: "text-red-600",
      stat: "ONLINE",
      disabled: false,
    }
  ];